# Generated by Django 5.2.6 on 2026-02-17 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='gty',
            new_name='qty',
        ),
    ]
