# Generated by Django 5.2.6 on 2025-09-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('post', models.CharField(max_length=20)),
            ],
        ),
    ]
