# Generated by Django 5.2.6 on 2025-10-07 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='cat_img')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('peice', models.FloatField()),
                ('qty', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='prod_img')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vegetableapp.category')),
            ],
        ),
    ]
