# Generated by Django 5.2.6 on 2025-12-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetableapp', '0004_userorder_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='orderid',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
