# Generated by Django 5.2.6 on 2025-11-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default=0, upload_to='profile_pic'),
            preserve_default=False,
        ),
    ]
