# Generated by Django 5.2.6 on 2025-10-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='test', upload_to='profiles'),
        ),
    ]
